# Generated by Django 6.0.3 on 2026-04-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='title',
            new_name='subtitulo',
        ),
        migrations.RemoveField(
            model_name='page',
            name='author',
        ),
        migrations.RemoveField(
            model_name='page',
            name='content',
        ),
        migrations.RemoveField(
            model_name='page',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='page',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='page',
            name='contenido',
            field=models.TextField(default='texto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='fecha',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='titulo',
            field=models.CharField(default='titulo', max_length=100),
            preserve_default=False,
        ),
    ]
