# Generated by Django 6.0.3 on 2026-04-02 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_mensaje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
